# Generated by Django 4.2 on 2023-04-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='colours',
            field=models.ForeignKey(help_text='Введите цвет сумки', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='catalog.colours', verbose_name='Цвет сумки'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='material',
            field=models.ForeignKey(help_text='Введите материалы сумки', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='catalog.material', verbose_name='Материалы сумки'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Введите описание сумки'),
        ),
    ]
