# Generated by Django 4.2 on 2023-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bag_colours_alter_bag_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Картинка сумки')),
            ],
        ),
        migrations.AddField(
            model_name='bag',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение', null=True, upload_to='', verbose_name='Картинка сумки'),
        ),
    ]
