# Generated by Django 4.2 on 2023-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_imagebag_bag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение', null=True, upload_to='media', verbose_name='Картинка сумки'),
        ),
        migrations.AlterField(
            model_name='imagebag',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Картинка сумки'),
        ),
    ]
