# Generated by Django 4.2 on 2023-05-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_imagebag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Статус экземпляра'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='colours',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='catalog.colours', verbose_name='Цвет сумки'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='material',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='catalog.material', verbose_name='Материалы сумки'),
        ),
    ]
