# Generated by Django 4.2 on 2023-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bag_status_alter_bag_colours_alter_bag_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите стоимость сумки', max_length=20, verbose_name='Стоимость сумки')),
            ],
        ),
        migrations.AddField(
            model_name='bag',
            name='cost',
            field=models.CharField(help_text='Стоимость сумки', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='summary',
            field=models.CharField(max_length=1000, verbose_name='Введите описание сумки'),
        ),
    ]
