# Generated by Django 4.2 on 2023-05-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_bag_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crest', models.ImageField(help_text='Загрузите изображение', null=True, upload_to='media', verbose_name='Картинка крестика')),
            ],
        ),
    ]
