# Generated by Django 4.2 on 2023-05-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='textfield',
            field=models.CharField(max_length=20, null=True, verbose_name='тестовый текст'),
        ),
    ]
